services:

  rails:
    build: rails
    volumes:
      - ./rails:/rails
    ports:
      - 3000:3000
    environment:
      DATABASE_URL: postgres://postgres@postgres/postgres
    depends_on:
      - postgres
    command: rails server --binding=0.0.0.0

  postgres:
    image: postgres:15
    volumes:
      - postgres:/var/lib/postgresql/data
    ports:
      - 5432:5432
    environment:
      POSTGRES_HOST_AUTH_METHOD: trust

volumes:
  postgres: